# Generated by Django 3.0.1 on 2020-01-07 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_owner'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('votes', models.IntegerField()),
                ('creadted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='threads.Threads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
    ]
